dist: trusty
arch: ppc64le
sudo: required

language: go

env:
  global:
    - secure: "SSGPlBUXMb2F3ycFEvRKHoftYy0UkIprwgtfOKXU/Uc359Qct+IrF/b8GuTd64tedXtnQE4z4fxqT8wdYRdNwUysmOvRyzlNTRhs1gocx5iL5El8+7F4we7wElh6ckt2Z5AVI5g0JOwYeQNURFhgDumN14K8XsOu7a2LzRBVFRn55z79xgTL+JnTI89JIWjz1QCr8Z054CMaK0MHJRLkgPnbnx1Skra3Wt16g29wRZLqLWoU8lyrLy9Ao/yHw/AJMCNie8ah7nNiOEdgPTcr/onZ/v+eVyaTvzE9UrmdeqpUpASypAAUnmZ9Q6QsU31dVxwbfPB0r8TzrqinCOYMnHbU/3fIz49Q+yv7RyifYsTlnx7+J79LmCvs7X+iKkmOprWdBRwUUxzDhwgIGnmBlYf0nKj9H2U3XFCYDnbRSI9ZugGBprs3t09w15gwq/wLM6DhY87zNhM4Vfb34ZXVBCEhtUXKUVbVthiPOWlHtbs0YympG/QCV+27tVIszgek8FFt6/fJeEh/APNadK9fuU01ozB01aXj0xMl3PlvoWWeQXDnyttHEWRaiVpbPKGoV5a7LPCVpWk5EOX8YNgHEUnjKwfzVBUriXAd+8zp0sx6TRdt1ts7x04NP1yFF1SCXXBpz/geOsfa2bBQyJx6y7CODcmW7fbcJLxmwdGlm6E="
    - secure: "Tr9KxWvfQS6BSF1qUqz1Q41le5k/c+L37Aq8wTPQcmXVu8nLv5T1QMarx64KfZ2qaQBRV+M6DwnJQM7HU/cWX9AKpdoAO2INqANfoFLh8XTR5ncHjaNTzi9aS7owxa+9t0yfKowq7s4dp96nqmwchYFtUxpzKo0TMOcQ1l1AGEu5liniXb9VOKgG8UAZsLgD6b2a80nn6NP1JehGGxcWsow0EzxalnJ8Cv78YTLmqGNowYh5UmkhjkxqE4TskQafRd2qtYMPvxnC2CFd8G3qMlbBzCxM02lGKwbr/Vi41hcSyD3uuyaKVHr/g5qLcp/HNyrUGTREL1UvWkWjlL6ovuh6uHYlnpVwQkX5fzUH7z2hlr9HjQ3Tu6Sbh1CX5QBR5PUkvoOfdx0BHTmTTw2xkvUDHarqZT1OkMuUplCY/VMnJaqa5ko126r8CyKYqRoT4HQuqa6szVawGiB211VCQXJRVyLYtKUGO6mmnMUoi5H676/sv6c9py8bieMoyEyrI87lS0AhQ6QLnTjNbEO5xt6vFi7rEgcctD5nuEBwb/X2bmM2OdZFYXrIbXaZfq7fRKyzCQthfceCmySExOGI9ndCE/mS68X6NNFBVsVwb7zt0zSY6oGlf0/N2CR5sf8gwKYG1scr5Jyqmuifvqv433zepA0Sxj6WqC3ixlssNd8="
jobs:
  include:
    # YAML alias, for settings shared across the tests
    - &base-test
      stage: test
      go_import_path: github.com/openshift/odo
      go: "1.11.2"
      install:
        - make goget-tools
        # binary will be $(go env GOPATH)/bin/golangci-lint
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      script:
        - export PATH="$PATH:$GOPATH/bin"
        - make bin
        - make validate
        - make test-coverage
        - make golint
      after_success:
        # submit coverage.txt to codecov.io
        - bash <(curl -s https://codecov.io/bash)

    - <<: *base-test
      stage: test
      name: "generic, login, component command integration tests"
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - odo login -u developer
        - travis_wait make test-generic
        - travis_wait make test-cmd-login-logout
        - travis_wait make test-cmd-cmp
        - odo logout

    - <<: *base-test
      stage: test
      name: "preference, config, url and debug command integration tests"
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - odo login -u developer
        - travis_wait make test-cmd-pref-config
        - travis_wait make test-cmd-url
        - travis_wait make test-cmd-debug
        - odo logout

    # Run service-catalog e2e tests
    - <<: *base-test
      stage: test
      name: "service, link, component sub-commands command integration tests"
      script:
        - ./scripts/oc-cluster.sh service-catalog
        - make bin
        - sudo cp odo /usr/bin
        - odo login -u developer
        - travis_wait make test-cmd-service
        - make test-cmd-link-unlink
        - travis_wait make test-cmd-cmp-sub
        - odo logout

    - <<: *base-test
      stage: test
      name: "watch, storage, app, project and push command integration tests"
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - odo login -u developer
        - travis_wait make test-cmd-watch
        - travis_wait make test-cmd-storage
        - travis_wait make test-cmd-app
        - travis_wait make test-cmd-push
        - travis_wait make test-cmd-project
        - odo logout

    - <<: *base-test
      stage: test
      name: "core beta, java, source e2e tests"
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - odo login -u developer
        - travis_wait make test-e2e-beta
        - travis_wait make test-e2e-java
        - travis_wait make test-e2e-source
        - odo logout

    # test installation script on linux
    # - stage: test
    #   services:
    #     - docker
    #   install:
    #     - true
    #   script:
    #     ./scripts/test-install.sh
    # test installation script on macOS
    # - state: test
    #   os: osx
    #   install:
    #     - true
    #   script:
    #     ./scripts/installer.sh
